// STARTER CONTENT — NOT LEGAL ADVICE.
// This page is a draft template for a one-person Indian digital-products
// business. It has not been written or reviewed by a lawyer. Review,
// customize (see the {/* EDIT: ... */} markers below) and get it checked by
// a qualified professional before relying on it for a live business.

import LegalPageLayout from "../components/LegalPageLayout";
import { usePageMeta } from "../hooks/usePageMeta";
import { PRODUCT_NAME, SUPPORT_EMAIL } from "../config";

export default function Terms() {
  usePageMeta({
    title: "Terms and Conditions | PRODXSTORE",
    description: `Terms and conditions for purchasing ${PRODUCT_NAME} from PRODXSTORE.`,
    robots: "index, follow",
  });

  return (
    // EDIT: set the real "last updated" date whenever you revise this page.
    <LegalPageLayout title="Terms and Conditions" lastUpdated="1 August 2026">
      <p>
        These Terms and Conditions ("Terms") govern your purchase and use of {PRODUCT_NAME} and
        any other digital products sold by PRODXSTORE ("we", "us", "our"). By purchasing or
        downloading our products, you agree to these Terms.
      </p>

      <h2>1. What you're buying</h2>
      <p>
        {PRODUCT_NAME} is a digital product — a downloadable collection of AI prompts supplied as
        CSV files. There is no physical item shipped. Access is delivered digitally, typically
        immediately after successful payment.
      </p>

      <h2>2. License to use the prompts</h2>
      <p>Once purchased, you are granted a license to:</p>
      <ul>
        <li>Use the prompts for your own personal projects.</li>
        <li>
          Use the prompts for commercial and client work, including work you are paid for.
        </li>
        <li>
          Use content, images, video or text you generate using the prompts, subject to the terms
          of the AI platform you use to generate it.
        </li>
      </ul>
      <p>You may not:</p>
      <ul>
        <li>
          Resell, redistribute, share publicly or re-upload the prompt files themselves (the CSV
          files or their contents as a standalone product).
        </li>
        <li>
          Repackage the prompts, in whole or substantial part, as a competing prompt bundle or
          product for sale.
        </li>
        <li>Claim authorship of the prompt collection itself.</li>
      </ul>

      <h2>3. "As-is" — no warranty</h2>
      <p>
        The product is provided "as is" and "as available", without warranties of any kind,
        whether express or implied, including but not limited to warranties of merchantability,
        fitness for a particular purpose, or non-infringement. Results generated by AI tools using
        these prompts can vary and are not guaranteed. We do not guarantee that any AI platform
        will interpret a prompt identically to the examples shown on our website.
      </p>

      <h2>4. Payment and delivery</h2>
      <p>
        Purchases are processed through our payment partner
        {/* EDIT: name the actual gateway(s) you use, e.g. SuperProfile / Razorpay / PayPal */}{" "}
        (SuperProfile, which may use Razorpay or another payment processor). This is a one-time
        payment — there is no recurring subscription. Delivery is instant and digital; access
        instructions are shown on the confirmation page and sent to the email address used at
        checkout.
      </p>

      <h2>5. Refunds</h2>
      <p>
        Refund requests are handled under our{" "}
        <a href="/refund-policy">Refund Policy</a>, which includes a 7-day money-back guarantee
        subject to the conditions described there.
      </p>

      <h2>6. Limitation of liability</h2>
      <p>
        To the maximum extent permitted by law, PRODXSTORE will not be liable for any indirect,
        incidental or consequential damages arising from your use of the product, including
        outcomes produced by third-party AI tools.
      </p>

      <h2>7. Governing law</h2>
      <p>
        These Terms are governed by the laws of India.{" "}
        {/* EDIT: specify your state/city for jurisdiction, e.g. "Courts in [City], [State] will have exclusive jurisdiction." */}
      </p>

      <h2>8. Changes to these Terms</h2>
      <p>
        We may update these Terms from time to time. Continued use of the product after changes
        are posted constitutes acceptance of the revised Terms.
      </p>

      <h2>9. Contact</h2>
      <p>
        Questions about these Terms? Email{" "}
        <a href={`mailto:${SUPPORT_EMAIL}`}>{SUPPORT_EMAIL}</a>.
      </p>
    </LegalPageLayout>
  );
}
